### ISSUE TITLE
[solved] Error with latest commit and sb option

### ISSUE THREAD

**Issue by LauraKim** [tomslee/airbnb-data-collection#10]
Hi there,

I updated to the latest commit and now have this error. (not sure what commit I was using before that - a month old at least)

```
INFO    Found 18 rooms
ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "./airbnb.py", line 2059, in ws_search_rectangle
    listing.property_type = json_listing["property_type"]
KeyError: 'property_type'
ERROR   Error
Traceback (most recent call last):
  File "./airbnb.py", line 1186, in __search_loop_bounding_box
    rectangle_zoom, flag)
  File "./airbnb.py", line 1271, in __search_rectangle
    rectangle, rectangle_zoom, flag)
  File "./airbnb.py", line 2059, in ws_search_rectangle
    listing.property_type = json_listing["property_type"]
KeyError: 'property_type'
INFO    Searching by bounding box - logged
```

Any idea what may have caused this issue?

Thank you

**Comment by tomslee** [comment]
Hi Laura,

I reproduced this today. I suspect a change in the Airbnb web site format, but I will try this evening and let you know.

Tom

**Comment by tomslee** [comment]
Airbnb had indeed changed the format. I have fixed the bug but no longer get property_type information. To be clear, the script does still get room_type (Entire home/apt, Private room, or Shared room), but does not get property_type (apartment, tree house, etc), which it did not get anyway until recently.

**Comment by LauraKim** [comment]
That works great again!
I was not using the property_type anyway.

**Comment by LauraKim** [comment]
Do we know what is the list of "property_type_id":x 
It would actually be interesting to know which are "holiday houses" or anything that is tourist related.
