### ISSUE TITLE
Error json "returning None"

### ISSUE THREAD

**Issue by clairebqt** [tomslee/airbnb-data-collection#11]
Hi, 
Usually the script works very well, but now I have this error at every pages scrape and 0 room in database:

```
Searching 'Private room' (1 guests, prices in [60, 80]), zoom 0
2017-01-16 15:29:47,996 INFO    Page 1...
2017-01-16 15:29:49,728 ERROR   Error in __listing_from_search_page_json: returning None
2017-01-16 15:29:49,728 ERROR   Error in __listing_from_search_page_json: returning None
2017-01-16 15:29:49,729 INFO    Private room (1 guests): zoom 0: 0 new rooms, 1 pages
```

Do you have an idea what may cause the issue?

Thank you
Claire

**Comment by tomslee** [comment]
Hi Claire: Can I ask if you are using the current code? I have had to make some changes recently and may have introduced this problem, but I think it is a solved one (not sure though). If you are on the most recent:
- can you say what command you are running? (-s, -sb, -sz). 
- if you can tell me what city you are looking at that might help too, but if you'd rather not then I don't think it is an issue.

**Comment by clairebqt** [comment]
I thought using the current code, I download the code again and it works well with the command -sb
