### ISSUE TITLE
Error: column "coworker_hosted" of relation "room" does not exist

### ISSUE THREAD

**Issue by PeteLambert** [tomslee/airbnb-data-collection#12]
First time user, just downloaded latest commit with -sb method, now getting this error:

Searching 'Private room' (1 guests, prices in [0, 40]), zoom 0
Page 1...
ERROR   Exception in get_search_page_info_rectangle
Traceback (most recent call last):
  File "airbnb.py", line 206, in save
    self.__insert()
  File "airbnb.py", line 362, in __insert
    cur.execute(sql, insert_args)
psycopg2.ProgrammingError: column "coworker_hosted" of relation "room" does not exist
LINE 7:                     coworker_hosted, extra_host_languages, n...
                               ^

All help appreciated, thank you kindly,

Peter

**Comment by tomslee** [comment]
That's a column I added recently. There's a script in the repo called schema_update.py and if you run that it should make the change for you and add the column.

**Comment by PeteLambert** [comment]
Thank you Tom.
