### ISSUE TITLE
Airbnb change breaking the collection script

### ISSUE THREAD

**Issue by tomslee** [tomslee/airbnb-data-collection#14]
I have heard from a couple of users that collection has been broken by an update to the Airbnb web site. I have been unable to work on it this week, but hope to have this done by Sunday Feb 12, so long as it's just a tweak that is needed.

**Comment by harrykipper** [comment]
Removing integer conversion of self.coworker_hosted in `__insert` makes collection run fine again (what is "coworker hosted" anyway?). This is `int(self.coworker_hosted)` 

However bathrooms and minstay are always NULL :-/

**Comment by tomslee** [comment]
Fixed. Thanks Mr Kipper. bathrooms and minstay don't seem to be included in the search page json response, which is why they are NULL (unless I missed them). You could add them in by running -f afterwards (to pick them up from the listing pages) but that takes a lot longer of course. And I don't know what coworker_hosted means but I figure collect it while I can.

**Comment by tomslee** [comment]
Meant to close the issue.
