### ISSUE TITLE
Error with python airbnb.py -asa "Paris"

### ISSUE THREAD

**Issue by diouck** [tomslee/airbnb-data-collection#15]
Hello I am very interested in your work but I come across this error and I can not solve it
python airbnb.py -asa "City Name"

2017-02-17 23:42:19,461 ERROR   Failed to add survey for Paris
2017-02-17 23:42:19,462 ERROR   Top level exception handler: quitting.
Traceback (most recent call last):
  File "airbnb.py", line 2394, in main
    db_add_survey(ab_config, args.addsurvey)
  File "airbnb.py", line 1613, in db_add_survey
    survey_id = cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

Is what you can me debegger

Thanks

**Comment by diouck** [comment]
python airbnb.py -asa "Paris"

**Comment by iamishalkin** [comment]
for me it works fine

**Comment by Luisbalmeida** [comment]
I have this error 

C:\airbnb>python airbnb.py -asv "lisboa" -c u.config
ERROR:root:Failed to add survey for lisboa
ERROR:root:Top level exception handler: quitting.
Traceback (most recent call last):
  File "airbnb.py", line 442, in main
    db_add_survey(ab_config, args.addsurvey)
  File "airbnb.py", line 148, in db_add_survey
    survey_id = cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by tomslee** [comment]
Have you added "lisboa" as a search_area first? You need to do "python airbnb.py -asa Lisboa -c u.config" first.

**Comment by Luisbalmeida** [comment]
C:\airbnb>python airbnb.py -asa Lisboa -c casa.config
OK

C:\airbnb>python airbnb.py -asv "lisboa" -c casa.config
ERROR:root:Failed to add survey for lisboa
ERROR:root:Top level exception handler: quitting.
Traceback (most recent call last):
  File "airbnb.py", line 442, in main
    db_add_survey(ab_config, args.addsurvey)
  File "airbnb.py", line 148, in db_add_survey
    survey_id = cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by tomslee** [comment]
PostgreSQL is case sensitive, so your second command would have to be -asv Lisboa, not -asv lisboa.

**Comment by carancib** [comment]
I'm having the same issue, could you please help me solve this?

MacBook-Air-de-Carlos:airbnb-data-collection-master carlosarancibia$ python airbnb.py -asa "Santiago"
MacBook-Air-de-Carlos:airbnb-data-collection-master carlosarancibia$ python airbnb.py -asv "Santiago"
ERROR:root:Failed to add survey for Santiago
ERROR:root:Top level exception handler: quitting.
Traceback (most recent call last):
  File "airbnb.py", line 442, in main
    db_add_survey(ab_config, args.addsurvey)
  File "airbnb.py", line 148, in db_add_survey
    survey_id = cur.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable

Thanks

**Comment by tomslee** [comment]
Judging from where the error is, it looks like the -asa command failed to add Santiago to the search_area table. Please could you check that with "SELECT * FROM search_area"?

I'm going to guess that the "name" column of the search_area table holds something different from "Santiago". If that is the case, then you should update the table using "UPDATE search_area SET name = 'Santiago' WHERE search_area_id = <your search_area_id>".

Currently I am maintaining only the -sb search type, so you would need to update the row with a bounding box before doing a search.

**Comment by carancib** [comment]
Thanks Tom, i created the survey id manually and the survey area.
My only issue now is that the bathroom numeric column shows null for all entries. It seems they changed something, but bedrooms are working just fine

**Comment by tanjavollmer** [comment]
Same issue, different error. Could you help?

ERROR   Error collecting city and neighborhood information
ERROR   Error getting city info from website
ERROR   Top level exception handler: quitting.

Thank you.

**Comment by carancib** [comment]
Tanja what worked for me was manually creating the search_area_id with the bounding box for my city (search_area table) and then creating a survey with that search area in the survey table
Then you just run a -sb search with the survey id code

**Comment by tanjavollmer** [comment]
Thanks carancib for your superfast response! As you said, I manually created the search_area_id as well as the survey_id. Could you tell me how to now run the search with the survey id code? In other words, what should I type after "-sb ..." if the survey I want to run has the survey_id "1"? 

Thanks!!

**Comment by tanjavollmer** [comment]
Solved. Thank you carancib :-)
