### ISSUE TITLE
exception missing

### ISSUE THREAD

**Issue by nadavbi** [tomslee/airbnb-data-collection#20]
Function add_survey_log_bb_table in schema_update.py is missing an exception as part of the Try function, This leads to unexpected unindent error

**Comment by tomslee** [comment]
Hi nadavbi: sorry about that. I believe it is fixed now. The perils of developing on the master branch: I will try to avoid doing so in future.

**Comment by nadavbi** [comment]
Hey,
schema_update.py is still unfixed. 
Thanks for the response!

**Comment by tomslee** [comment]
My bad. Can you try again please? Unfortunately I don't have a good test setup for schema changes...

**Comment by nadavbi** [comment]
This worked, but apparently this wasn't the source of the error I was getting (all of my schemas are updated)
I get a bunch of errors when beginning the bounding box method in the type of:

> rectangle = self.bounding_box[0:4]
> TypeError: 'NoneType' object is not subscriptable

I will mention that that the bounding coordinates are entered and I've been using this method for a while. It's just since I tried the updated the code that this error exists

**Comment by tomslee** [comment]
I'll take a look this evening. I've been using it for a while before checking in changes so it works for me, but obviously we have things set up slightly differently.

**Comment by tomslee** [comment]
I am not seeing anything obvious about why self.bounding_box can end up as None. Do you think you could run it again like this to get debug output:
`python airbnb.py -sb NNN -v`
and then attach the log file to the issue, or email it to me at tom at tomslee dot net if you prefer.
