### ISSUE TITLE
Price hidden behind Javascript?

### ISSUE THREAD

**Issue by henlueth** [tomslee/airbnb-data-collection#22]
First of all thanks for your amazing work. I noticed that the code for get_price doesn't work for me, since requests.get doesn't fetch the respective element ("//meta[@itemprop='price']"). Hence the value for price is None. I tried a workaround using Selenium and it worked. Am I doing something wrong or is the scraper broken at the moment? Thanks!

**Comment by tomslee** [comment]
Hi henlueth,

The scraper is giving prices properly for me for a number of cities.
It looks like you are not using the most recent version of the script? It gets the price from a json document returned from the site now, rather than scanning the html.

**Comment by henlueth** [comment]
Thanks, I indeed just tried to update the old script with the new path. I will give it a try with the new version of the script.

**Comment by henlueth** [comment]
Hi, the problem is now even more relevant than before. Almost all important information is in the location with the xpath '//*[@id="site-content"]/script[@data-hypernova-key="p3show_marketplacebundlejs"]/text()'  and without javascript the element's content is not loaded without Selenium.

**Comment by tomslee** [comment]
I'm getting different JavaScript in the current version, so I'm closing this issue.
