### ISSUE TITLE
Error in schema_current.sql

### ISSUE THREAD

**Issue by pmsousa** [tomslee/airbnb-data-collection#23]
Hi,

I'm trying to build the database using a Docker postgresql container but I'm struggling with schema errors both on schema.sql and schema_current.sql.
I first tried with the schema_current.sql but when building the schema I get an error on the CREATE TABLE public.city:

`ERROR:  relation "city_city_id_seq" does not exist
STATEMENT:  CREATE TABLE public.city
        (
          city_id integer NOT NULL DEFAULT nextval('city_city_id_seq'::regclass),
          name character varying(255),
          search_area_id integer,
          CONSTRAINT city_pkey PRIMARY KEY (city_id)
        )
        WITH (
          OIDS=FALSE
        );
psql:/docker-entrypoint-initdb.d/3-schema_current.sql:10: ERROR:  relation "city_city_id_seq" does not exist`

I've noticed the change between the schema_current.sql and the schema.sql. On the older file (schema.sql) the table was built first, then the SEQUENCE _city_city_id_seq_.

Can you help me?

PS: The final goal is to construct a docker service with a series of containers for data (postgresql), code (pyhton) and frontends (to be determined...).

Thanks,
Pedro

**Comment by pmsousa** [comment]
@tomslee, any news on this request?

**Comment by tomslee** [comment]
I've been absent (sick, vacation,...). Will take a look this weekend.

**Comment by deroses** [comment]
Had same issue - you need to move the sequence creates before the table creates.  You'll also need to add the postgis extension from the original schema.sql so the geometry call will work.  I'll make a PR with this new sql file if you'd prefer.

[schema_current.sql.txt](https://github.com/tomslee/airbnb-data-collection/files/1327264/schema_current.sql.txt)

**Comment by tomslee** [comment]
If you have the file that would be great.

**Comment by tomslee** [comment]
Thanks deroses for supplying a fixed schema_current.sql
