### ISSUE TITLE
Search finishes without starting and problems making a new 'asa'

### ISSUE THREAD

**Issue by chriotte** [tomslee/airbnb-data-collection#28]
Hi,

first of all, great job with this project! I'm trying to get your code to work, and after adding a search area and a survey, I start the survey with 'python airbnb.py -s 1', but it never seems to find anything and finishes in less than a second. I've tried to create a survey for London twice, and Paris once, but the result is the same regardless. 
Is this just a problem I'm having, or have AirBnb updated their website since the last commit? (The master code didn't work at all for me, so I'm using the code on the dev branch)

python airbnb.py -s 1
INFO    ======================================================================
INFO    Survey 1, for London
INFO    Searching by neighborhood
INFO    Finishing survey 1, for London

Additionally, it seems to have troubles connecting to AirBnb? Often when I add a new 'asa' it fails, but when I retry it a few times magically works.  

python airbnb.py -asa "London"
ERROR   Error collecting city and neighborhood information
ERROR   Error getting city info from website
ERROR   Top level exception handler: quitting.
Traceback (most recent call last):
  File "airbnb.py", line 444, in main
    ws_get_city_info(ab_config, args.addsearcharea, ab_config.FLAGS_ADD)
  File "airbnb.py", line 271, in ws_get_city_info
    conn.commit()
UnboundLocalError: local variable 'conn' referenced before assignment

do you have any idea what could result in these problems? 

edit: Just FYI I'm running a Postgres DB in AWS, and I've tried to run the scripts both directly on my Mac, and through an EC2 instance. Entries in the DB is updated when I add e.g London, so the connection definitely works to the DB both within AWS and from my local Mac.

**Comment by tomslee** [comment]
Hi Christopher,

Unfortunately the Airbnb web site has made two sets of changes this year,
and as soon as I fixed it for the first one, the second one broke the
script. Now I won't have time to fix it until April, unfortunately. I'll
try to get to it in early April.

Sorry for the frustration,

Tom

**Comment by chriotte** [comment]
Hi Tom,

Thanks for coming back to me on this, it's frustrating (even more for you I assume) that Airbnb keeps changing the website layout. I might have some time to look at this problem next week if I get things to work I'll send in a pull request. 

Thanks for the great work done in this repo so far! 👍 

Christopher

**Comment by LauraKim** [comment]
Keep up the good work Tom!
See you in April hopefully.

**Comment by ralik** [comment]
I was about to do my April dump but yeah... Same problem here.
Thanks a lot for this beautiful script Tom. Hopefully you will have some clue to how to bypass airbnb new changes.
Ra

**Comment by tomslee** [comment]
Sorry folks: yes the script is bust right now. I had just fixed it for an earlier change when Airbnb changed it again. I think it's because they now have more room_types than the original three, but not sure. I do hope to have a look in the next few days but have not been able to spend time on this recently.

**Comment by tomslee** [comment]
I have uploaded a change that makes searches possible again -- see the README for some details. In an ideal world I would do more testing first, but this is better than a broken script. Only "-sb" works for now: I hope to fix the -asa problem very soon.

**Comment by rabany** [comment]
I'm sorry for posting my previous post here. I transfer it to a new issue.

**Comment by tomslee** [comment]
The version checked in today finally fixes the "-asa" problem. It only adds a row into the database (search_area table) instead of going to the Airbnb web site. As only the bounding box search works, you need to update the row with the coordinates of a bounding box. See the README for details on that.
