### ISSUE TITLE
Running by bounding box

### ISSUE THREAD

**Issue by feferri** [tomslee/airbnb-data-collection#29]
Hello, I'm trying to run by the bounding-box as the last recommendation but it seems is not working. I've tried 3 cities: 'SAO PAULO'; 'LISBON'; 'MIAMI' adding manually the city name and the bounding-box info into search_area. Then, when I run the script it's kind of eternal looping trying to connect to the airbnb server. 

Tks

**Comment by feferri** [comment]
WARNING No response received from request despite multiple attempts: {'source': 'filter', 'refinement_paths[]': 'homes', 'sw_lat': '-22.74603', 'sw_lng': '-43.0969', 'ne_lat': '-22.74603', 'ne_lng': '-43.0969', 'search_by_map': 'True', 'section_offset': '18'}
WARNING Network request exception 0: connectionError
WARNING Network request exception 1: connectionError
...

**Comment by feferri** [comment]
INFO    Retrieved logged progress: None, None guests, price None-None
INFO            quadtree node [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
INFO            median node [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
INFO    Bounding box: [-22.746033, -43.096904, -23.082229, -43.79506]
INFO    ======================================================================
INFO    Survey 7, for Rio de Janeiro
INFO    Searching by bounding box, max_zoom=6
INFO    ----------------------------------------------------------------------
INFO    Rectangle calculated: [-22.74603, -43.0969, -22.74603, -43.0969]
INFO    Searching rectangle: zoom factor = 49, node = [[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]

**Comment by tomslee** [comment]
I hope this was because of problems when running without a proxy. If you are still interested, could you try again?
