### ISSUE TITLE
Thank you for this very good work but I have problems with bounding box method

### ISSUE THREAD

**Issue by rabany** [tomslee/airbnb-data-collection#31]
Congratulations on this great job ... questioned regularly by the random changes of Airbnb.

After doing this:
`python airbnb.py -asa "Bordeaux"`
`python airbnb.py -asv "Bordeaux"`
`update search_area set bb_n_lat = 44.92, bb_s_lat = 44.81, bb_e_lng = -0.53, bb_w_lng = -0.64 where name = 'Bordeaux';`
`python airbnb.py -sb 1`

, I get this:
`INFO Bounding box: [44.92, -0.53, 44.81, -0.64]`
`INFO ===========================================================`
`INFO Survey 1, for Bordeaux`
`INFO Searching by bounding box, max_zoom=6`
`INFO ----------------------------------------------------------------------`
`INFO Rectangle calculated: [44.92, -0.53, 44.81, -0.64]`
`INFO Searching rectangle: zoom factor = 0, node = []`
`INFO Page 01 returned 06 listings`
`INFO Results: 1 pages, 6 new rooms`
`INFO Finishing survey 1, for Bordeaux`

and 6 records in the room table:
`room_id;host_id;room_type;country;city;neighborhood;address;reviews;overall_satisfaction;accommodates;bedrooms;bathrooms;price;deleted;minstay;last_modified;latitude;longitude;survey_id;location;coworker_hosted;extra_host_languages;name;property_type;currency;rate_type`
`1582859;8426743;"Entire home/apt";"";"";"";"";236;5;4;0.00;1.00;67;0;;"2018-04-24 16:06:20.450171";44.458536;-68.483788;1;"0101000020E6100000A08CF161F61E51C0F304C24EB13A4640";;"";"Coastal Maine Cottage";"";"EUR";"nightly"`
`10201545;9991820;"Entire home/apt";"";"";"";"";148;5;4;1.00;1.00;50;0;;"2018-04-24 16:06:23.570191";48.190689;16.267038;1;"0101000020E61000000CCA349A5C4430407D5A457F68184840";;"";"Sunny apartment near metro station.";"";"EUR";"nightly"`
`3993887;20703644;"Entire home/apt";"";"";"";"";142;5;2;0.00;1.00;34;0;;"2018-04-24 16:06:23.570191";4.488137;-75.697931;1;"0101000020E610000055F7C8E6AAEC52C0C6DE8B2FDAF31140";;"";"Romantic Cabana with view";"";"EUR";"nightly"`
`302695;1530306;"Entire home/apt";"";"";"";"";183;5;4;1.00;1.00;124;0;;"2018-04-24 16:06:23.570191";46.043525;9.252129;1;"0101000020E610000012BF620D178122407AC7293A92054740";;"";"Romantic, Lakeside Home with Views of Lake Como";"";"EUR";"nightly"`
`5116533;26439805;"Entire home/apt";"";"";"";"";282;5;4;0.00;1.00;57;0;;"2018-04-24 16:06:23.570191";31.250417;121.484245;1;"0101000020E61000001990BDDEFD5E5E40C85C19541B403F40";;"";"#2 SHANGHIGH HOME";"";"EUR";"nightly"`
`1016153;3937638;"Entire home/apt";"";"";"";"";119;5;2;1.00;1.00;69;0;;"2018-04-24 16:06:23.570191";-8.498757;114.965854;1;"0101000020E61000007DAD4B8DD0BD5C40594DD7135DFF20C0";;"";"BALIAN TREEHOUSE w beautiful pool";"";"EUR";"nightly"`

As you can see, there are several problems:
- address is empty,
- latitude and longitude are not in the required rectangle,
- there are only 6 listings.

I know that changes to the Airbnb site are already causing you a lot of problems, but I will be very touched if you could give me some time to solve these problems.

**Comment by deruci** [comment]
At least, I guess we can fix limited (6) listings problem by adding this snippet after line 667
```
if json_listings is None:
  continue
```

**Comment by tomslee** [comment]
I changed the request to get only the JavaScript from the web site, so I hope the "only 6" problem is fixed now. The downside is, you need to pick up a key by visiting the Airbnb web site in your browser. See the README for details.
