### ISSUE TITLE
Not sure about retrieving process is running right

### ISSUE THREAD

**Issue by luisencalada** [tomslee/airbnb-data-collection#34]
Hello Tom! I am getting this problem when searching by bbox... Warning HTTP Status 400 from web site: IP address blocked.Waiting 1.0 minutes... It seems my university IP is blocked... Do you have any recommendation to overpass this issue? When searching by zipcode or neighborhood, it finishes the process but no data is on DB.. Thanks in advance! I am looking for data within Lisbon boundaries

**Comment by joao** [comment]
Olá Luis,

Airbnb rate-limits requests, and you easily go over them for a city like Lisbon. So if you are at the University, with all the external connections having the same IP, it can even be the case of more students browsing normally the Airbnb website and just getting blocked.
The solution is to use proxy servers, as Tom suggests in the project README (check the Disclaimers section), to randomize your requests to Airbnb so you don't get blocked.

Also for Lisbon try instead search by Bounding Box, as zipcode method won't work and neighborhood as not as thorough as a few years ago.
Check my profile and drop me an email if there is anything specific to Portugal you want to check.
