### ISSUE TITLE
how to collect reviews textual data?

### ISSUE THREAD

**Issue by floswald** [tomslee/airbnb-data-collection#4]
hi @tomslee !

thanks for makign this code available. I was looking at the insideairbnb website where you also have reviews and calendars for each listing id. How do you collect that data? I can't seem to find it in this script here. Thanks for your help!
florian

**Comment by tomslee** [comment]
Hi Florian,

I am not affiliated with Inside Airbnb, although I have collaborated with
Murray Cox (who runs it) from time to time. His code and mine are separate,
so I am afraid I cannot help you with this.
