### ISSUE TITLE
IP address blocked

### ISSUE THREAD

**Issue by Poyias** [tomslee/airbnb-data-collection#40]
Hi,

This looks like a fantasic project. Thanks for sharing!
I am using bounding box, I updated the database 
and I keep getting:

WARNING HTTP status 400 from web site: IP address blocked. Waiting 1.0 minutes.

Is there something I am doing wrong?
How can I resolve this?

Thank you in advance,
Andreas

**Comment by Poyias** [comment]
I found it thanks!!
I had to change the api_key in the config file.

**Comment by tomslee** [comment]
Thanks for letting me and others know Poyias. Your comment may help other users who get stuck.

**Comment by scwp** [comment]
I'm having this issue as well despite having a valid API key in the config file. I've tried running it with proxies (many), without proxies, and using a VPN but I still get the HTTP status 400...IP blocked... message for every request. Is this something to do with the 'generic' API key or insufficient proxy setup (e.g. better quality proxies, more of them, etc.)?
