### ISSUE TITLE
Almost there...

### ISSUE THREAD

**Issue by jedfehrenbach** [tomslee/airbnb-data-collection#43]
I was able to set up the DB and install python requirements (although the latest Postgre 10, and python 3.7, with newer versions of requirements, sometimes), set up the config, and have created a bounding box in the DB, but when I run the "python airbnb.py -sb" option, while the script is running I get:

INFO    Rectangle calculated: [42.3232, -71.14235, 42.2946, -71.179]
INFO    Searching rectangle: zoom factor = 1, node = [[1, 1]]
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
ERROR   Operational error (connection closed): resuming
INFO    Page 01 returned 15 listings
INFO    Final page of listings for this search
INFO    Results: 1 pages, 0 new rooms
INFO    Finishing survey 1, for Brookline

In the end, nothing was written to "rooms" table.  Do you have any idea where I strayed off the path? I am a beginner with Postgre, but this kind of looks like a DB problem.  I am wondering if I need to uninstall python 37 and go with 34, and exact same versions of py requirements as in your requirements.txt file. Thanks for anyone's advice.

**Comment by tomslee** [comment]
Hi @jedfehrenbach . I can't get to my code for a few hours, but it does look like a database connection error. One thing to do would be to run "python airbnb.py -dbp" which just tries a database connection and prints whether it succeeded: at least that should tell you if you have the database connection set up properly.

**Comment by jedfehrenbach** [comment]
Hi Tom! Thank you for the response. 

That command is okay. I get:

'Connection test succeeded: airbnb@localhost'

I was also able to edit the table and create the bounding box coordinates just fine.

But I have problems running all the actual searches, whether by zip code, box, or neighborhood.

In pgAdmin4, I have a server named 'OSGIS' (in addition to a server called 'PostgreSQL 10', which was automatically created during install) then 'airbnb' and 'postgres' as databases within each server. Although that isn't the machine name. The machine is named itdgisweb16 and it is Windows Server 2016 OS. So I'm wondering if I need 'OSGIS' somewhere in the config file (or itdgisweb16), so that results write to the 'rooms' table. Or, perhaps I should delete OSGIS and go with the default server.

Thanks...much appreciated.

**Comment by jedfehrenbach** [comment]
Hi Tom,  just an update, everything is working fine. I think the issue ended up being either 1) something doesn't work with 64-bit of either Python 3.7 or Postgre/PostGIS, or 2) something doesn't work with the latest 10.x version of PostgreSQL. I ended up installing  32 bit of both Python 3.7 and PostgreSQL 9.5, and everything worked.  Thanks.

**Comment by tomslee** [comment]
Thanks for updating this @jedfehrenbach and sorry I had not replied. Unfortunately I don't get much time to work on this right now.
