### ISSUE TITLE
same page of listings returned

### ISSUE THREAD

**Issue by domatka78** [tomslee/airbnb-data-collection#47]
Hello Tom, thanks for your great work. 

I was wondering if Airbnb changed something recently (past week or so). Your code used to work perfectly but now it seems to return the same 18 rooms for page 01, 02, etc. in a given geographic area. Did some address in the API got changed? not sure. Thanks in advance.

**Comment by domatka78** [comment]
Fixed it, reporting here if someone needs help. Airbnb uses now items_offset instead of section_offset in the URL

**Comment by tomslee** [comment]
Many thanks for identifying the problem @domatka78. I've made a fix to the repository.
