### ISSUE TITLE
Airbnb API key

### ISSUE THREAD

**Issue by jhiwatig** [tomslee/airbnb-data-collection#49]
Hi,

Is there any way I can get an API key from Airbnb? The website says they are not accepting any requests at the moment. :(

Thanks.
Josh

**Comment by ARiisgaard** [comment]
The example.config has a small guide on how to find the API key:

# API Key
# To collect an API key using Chrome as your browser:
# - In your browser, go to the Airbnb web site 
# - From the menu button at the top right, open More Tools >  Developer Tools
# - Click the Network tab
# - In the Developer Tools, click the stop sign to clear the list of requests
# - Click XHR (this is the kind of event we want)
# - Move the map to generate a new search
# - Find a request with explore_tabs in the name, right click it to show
#   the URL in a new pane.
# - Find the key= part of the URL and add it here

Haven't had a chance to test if the key works, but the url does contain a key

**Comment by jhiwatig** [comment]
> The example.config has a small guide on how to find the API key:
> 
> API Key
> To collect an API key using Chrome as your browser:
> 
> * In your browser, go to the Airbnb web site
> * From the menu button at the top right, open More Tools >  Developer Tools
> * Click the Network tab
> * In the Developer Tools, click the stop sign to clear the list of requests
> * Click XHR (this is the kind of event we want)
> * Move the map to generate a new search
> * Find a request with explore_tabs in the name, right click it to show
>   the URL in a new pane.
> * Find the key= part of the URL and add it here
> 
> Haven't had a chance to test if the key works, but the url does contain a key

Thanks man!

**Comment by tomslee** [comment]
Thanks @ARiisgaard .

**Comment by devmad001** [comment]
Hello
You should create developer account 
Then you can get API secret key
