### ISSUE TITLE
Proxy locations and fetched prices

### ISSUE THREAD

**Issue by bartgras** [tomslee/airbnb-data-collection#53]
I come from insideairbnb.com where it says "Tom Slee regularly scrapes the Airbnb site .." and in your readme I see "I run the script using a number of proxy IP addresses to ...".

Assuming that insideairbnb.com data was scraped using code from your repository, what are your thoughts on airbnb.com returning different results depending on your proxy's location?

To test this idea, I've used VPN to switch to different countries and checked prices for the same listing. Results are returned in local currency so if multiple proxies scrape single city, the resulting csv will also have prices with mixed currencies.

If you agree it's an issue, fetching currency symbol could be partially helpful. Example: One of the listings I've tested, when accessed from USA has price `$55`, from China `￥377` but from Canada `$74`.

**Comment by tomslee** [comment]
Hi @bartgras. Inside Airbnb has their own code, separate from (and probably better than) what's on here. I know they collect a lot more data per listing, for example.

I've used proxies in a single country, so I haven't seen the mixed problem you see. The script does retrieve the currency, and if you have a column named "currency" in the "room" table it should be filled in.

**Comment by bartgras** [comment]
Thank you Tom. That explains what I wanted to know.
