### ISSUE TITLE
Bounding box survey broken?

### ISSUE THREAD

**Issue by ecatkins** [tomslee/airbnb-data-collection#54]
I've been using the same process each month, for the last few months to run a survey over the same bounding box, successfully.

However attempting to do the same this month, the process finishes after just two pages (see log screenshot below)

Has there been a change to the Airbnb interface that might have broken this?

![image](https://user-images.githubusercontent.com/8319226/60398569-e6387400-9b27-11e9-9509-af29d6f4d495.png)

**Comment by domhaas** [comment]
Can confirm this. Currently I got the same issue.

In may I posted this issue: #52 
I thought it had something to do with missing proxy settings, but I think it's just the same issue. The strange thing is that later it worked again and currently it works in about 1 from 100 tries.

**Comment by ecatkins** [comment]
Latest commits have fixed this
