### ISSUE TITLE
To China user, site will redirect zh.airbnb.com, this's solution

### ISSUE THREAD

**Issue by lovaxi** [tomslee/airbnb-data-collection#6]
For china user, you need add some code to set locale to en, avoid auto redirect.

```
    # Now make the request
    cookies = dict(sticky_locale='en')
    response = requests.get(url, params, timeout=timeout,
                            headers=headers, cookies=cookies)
```

**Comment by lovaxi** [comment]
Otherwise, you will get bedrooms is null

**Comment by stevenyesz** [comment]
how about this issue?

**Comment by tomslee** [comment]
I had missed this. I've made the change but would like to run it for a few days to check that it makes no difference to other searches. I'll update this issue on the weekend.
