### ISSUE TITLE
[help] How to run schema(s) in postgresql

### ISSUE THREAD

**Issue by LauraKim** [tomslee/airbnb-data-collection#9]
Hi there,
This is not an issue but more of a help request to get the script running.
>  The schema is in the two files postgresql/schema.sql and postgresql/functions.sql. You need to run those to create the database tables to start with.
>
How do I run the schema(s) in order to create the tables? 
I think I have everything else setup properly. I am not at the step where it says "database "<airbnb>" does not exist.
Thank you

**Comment by tomslee** [comment]
Hi LauraKim and sorry for the slow reply. I would recommend getting a PostgreSQL client application like pgadmin (https://www.pgadmin.org/) which is a GUI app for managing PostgreSQL databases. You can open a Query window on a database and read the files into there. 

You do need to get yourself a PostgreSQL database first. I can't help with that, I'm afraid.

**Comment by LauraKim** [comment]
Hi Tom,
I have it running now.
However, python `airbnb.py -s survey_id` does not find the property_ids. Instead I get, "INFO    No property_ids: breaking" even though there are properties for this city.
Printing room_id information from the Airbnb web site does work (even though rooms are always marked as "deleted" for some reason).
